// Generated by CoffeeScript 1.9.2
module.exports = function(a, b, n, f) {
  var dx, dy, i, j, k, len, ref, results, results1, x, y;
  x = a[0];
  dx = a[0] === b[0] ? 0 : b[0] - a[0];
  y = a[1];
  dy = a[1] === b[1] ? 0 : b[1] - a[1];
  ref = (function() {
    results1 = [];
    for (var k = 0; 0 <= n ? k < n : k > n; 0 <= n ? k++ : k--){ results1.push(k); }
    return results1;
  }).apply(this).map(function(i) {
    return i / n;
  });
  results = [];
  for (j = 0, len = ref.length; j < len; j++) {
    i = ref[j];
    results.push(f([x + i * dx, y + i * dy]) === true);
  }
  return results;
};
